In [4]:
# !pip install -U Selenium

In [19]:
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import pandas as pd
import datetime

def scrap_option(keyword):
    driver = webdriver.Chrome()
    driver.get("https://www.google.com")

    search_field = driver.find_element("name", "q")
    search_field.send_keys(keyword)

    # Wait for the suggestion options to appear
    search_suggestions_locator = (By.XPATH, "//*[@id='Alh6id']/div[1]/div/ul/li")
    search_suggestions = WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located(search_suggestions_locator))


    # Extract and print the suggestion text
    # # Extract the text from the search results
    result_texts = [result.text for result in search_suggestions]

    driver.quit()

    longest_option = max(result_texts, key=len)
    shortest_option = min(result_texts, key=len)

    return longest_option, shortest_option

In [24]:
current_day_index = datetime.datetime.today().weekday()

# Map day index to day name
days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
current_day = days_of_week[current_day_index]

excel_file_path = 'excel.xlsx'

excel_data = pd.ExcelFile(excel_file_path)

if current_day in excel_data.sheet_names:
    data = pd.read_excel(excel_file_path, sheet_name=current_day)

In [25]:
data

    keyword keyword_list  longest_option  shortest_option
0  Keyword1        Dhaka             NaN              NaN
1  Keyword2       Sunday             NaN              NaN
2  Keyword3         Baby             NaN              NaN
3  Keyword4       School             NaN              NaN
4  Keyword5      Cricket             NaN              NaN
5  Keyword6        Momey             NaN              NaN
6  Keyword7          Int             NaN              NaN
7  Keyword8         Look             NaN              NaN
8  Keyword9        Hello             NaN              NaN

In [26]:
for idx, keyword in enumerate(data['keyword_list']):
    longest_option, shortest_option = scrap_option(keyword)
    data['longest_option'][idx] = longest_option
    data['shortest_option'][idx] = shortest_option
data

/tmp/ipykernel_30848/967265386.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['longest_option'][idx] = longest_option
/tmp/ipykernel_30848/967265386.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['shortest_option'][idx] = shortest_option

,keyword,keyword_list,longest_option,shortest_option
0,Keyword1,Dhaka,"ঢাকা বিশ্ববিদ্যালয়\nসরকারি বিশ্ববিদ্যালয়, ঢাক...",ঢাকা কলেজ
1,Keyword2,Sunday,sunday horror special\nসানডে হরর স্পেশাল — টিভ...,sunday
2,Keyword3,Baby,Baby Monster\nবেবি মনস্টার — মিউজিক্যাল গ্রুপ,baby
3,Keyword4,School,School 2017\nটিভি প্রোগ্রাম,school
4,Keyword5,Cricket,cricket icc\nআন্তর্জাতিক ক্রিকেট কাউন্সিল — ক্...,cricket
5,Keyword6,Momey,money cannot bring happiness story,money
6,Keyword7,Int,Inter Miami\nইন্টার মায়ামি সিএফ — ফুটবল টীম,inter miami vs
7,Keyword8,Look,lookism\nলুকিজম — কমিক বই ক্রম,look
8,Keyword9,Hello,Hello Kitty\nকাল্পনিক চরিত্র,hello world

In [28]:
with pd.ExcelWriter(excel_file_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
        writer.book = writer.book  # Load existing sheets
        data.to_excel(writer, sheet_name=current_day, index=False)

/tmp/ipykernel_30848/1441096117.py:2: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = writer.book  # Load existing sheets